apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DB_URL: "bW9uZ29kYitzcnY6Ly9Bc3dhbnRoOm1pY3JvbWF4Y2FudmFzQGNsdXN0ZXIwLnR1bHRrdjQubW9uZ29kYi5uZXQvdGVzdD9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA=="
  CLIENT_ID: "OTQ4NDY1MTQyNzk4LXZxbnZyZzZqdWdraGYwOHFjbTlrYWpocW1zdjYwZnR0LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t"
  CLIENT_SECRET: "R09DU1BYLURVYWxnMU9SRUpzS3ZUa29XUk9PdEJuSmZCbUM="
  REFRESH_TOKEN: "MS8vMDRmVy1ZQmpwemcwN0NnWUlBUkFBR0FRU053Ri1MOUlyN2FDbkFYSjgtanVlVFc1RS1FYW14OERjU3luLXAwZTdHQlN5Sy1xN3hlT2JGWXo4RWF3R0FLbE5VOHJrQlhrNGFUaw=="
  USER: "YXN3YW50aDJ0QGdtYWlsLmNvbQ=="
  PASS: "ZW96eSB5d3BsIGRhZ3kgeHB1bw=="
  JWT_SECRET: "bXlTZWNyZXQ="
  KEY_ID: "cnpwX3Rlc3RfbWZ2QUdvQ0pHMTNtTUU="
  KEY_SECRET: "TVkyV3JzZkdkVHp1bTRwNEFlSDQxTWs0"
