apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
