apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-admin
spec:
  selector:
    app: ecommerce-frontend-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend
spec:
  selector:
    app: ecommerce-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 
      nodePort: 30002
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-user
spec:
  selector:
    app: ecommerce-frontend-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
